### ISSUE TITLE
Generated code contains copyright statement in progenitor_client.rs

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/progenitor#244]
generated `progenitor_client.rs` contains
```
// Copyright 2022 Oxide Computer Company
...
```
This makes it unusable for my work purposes.  The company is happy to have MPL dependencies, but code in our repos needs to be free of other peoples copyrights.

It looks like the generated file is copy of https://github.com/oxidecomputer/progenitor/blob/main/progenitor-client/src/progenitor_client.rs .

Why not make the generated crate depend on https://crates.io/crates/progenitor-client ?

**Comment by jayvdb** [comment]
I guess the reason is that including the source code allows uncommitted/unreleased changes to `progenitor-client` to be accessed by the tests without needing to do tricky fiddling with the generated Cargo.toml to add `progenitor-client` using `path`.

**Comment by jayvdb** [comment]
https://github.com/oxidecomputer/progenitor/pull/246 is one approach.  This is my preference, as it also DRY's up the code a bit if there are multiple generated clients.

A simpler approach is to remove the copyright statement at the top of the "generated" file, but that doesnt completely really solve it because the "generated" file was copied from MPL project, and so it is implicitly MPL unless there is some explicit relicensing done during generation.

**Comment by ahl** [comment]
> Why not make the generated crate depend on https://crates.io/crates/progenitor-client ?

This was an intentional design choice. The project is evolving rapidly with infrequent updates to crates.io. Embedding the code within the generated crate means that we don't need to worry about dependencies in generated code on some support code not yet on crates.io.

I'd suggest you use the builder or macro form rather than the generated crate. If you need to use the generated crate then consider scripting the modifications you need to depend on the crates.io version of progenitor-client.

**Comment by jayvdb** [comment]
> If you need to use the generated crate then consider scripting the modifications you need to depend on the crates.io version of progenitor-client.

https://github.com/oxidecomputer/progenitor/pull/246 adds that possibility as a CLI flag.
