### ISSUE TITLE
type: number silently ignores `format` for integer types

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/progenitor#266]
The following is not ideal [OAS 3.0.3](https://swagger.io/specification/), as it defines a format which should be an integer, but uses `type: number` when the `type: integer` should be used.

However the following should emit an error of some sort, either a panic, or a stderr warning.

Currently the `format` value is silently ignored.

```yaml
type: number
format: int32
```

**Comment by ahl** [comment]
To what degree should progenitor / typify do validation of OpenAPI / JSON Schema? To what degree should it accommodate quirks and try to generate something useable versus balking at unfamiliar structures? Should it try to fix incorrectly specified specs? We need a pragmatic balance of the extremes.

My hope is that some resolution to https://github.com/oxidecomputer/typify/issues/58 will allow these kinds of adjustments by the consumer rather than these quirks into the crates themselves.

For the time being, can you modify the JSON document?

**Comment by jayvdb** [comment]
> For the time being, can you modify the JSON document?

Yes, we have modified our source doc, so this issue is not blocking us.

I like the idea at https://github.com/oxidecomputer/typify/issues/58#issuecomment-1339819688

> To what degree should progenitor / typify do validation of OpenAPI / JSON Schema?

Maybe not at all, if there is another tool which does this sufficiently.

https://github.com/oxidecomputer/openapi-lint is a great candidate for this validation being added, either as a lib or [as a bin](https://github.com/oxidecomputer/openapi-lint/issues/12).. ? ;-)  

I've looked at a few existing Rust tools which do not detect `{type: number format: int32}`
- https://github.com/blst-security/cherrybomb/
- https://github.com/kstasik/schema-tools/issues/66

I havent investigated whether these tools include this detection
- https://github.com/robjtede/oas3-rs
- https://github.com/JPMoresmau/openapi_validator/issues/1

Happy to include any other openapi linting/"schema validation" tools which anyone knows about.
