### ISSUE TITLE
`field already declared` when using the Builder interface with a parameter called: `client`

### ISSUE THREAD

**Issue by dmeijboom** [oxidecomputer/progenitor#288]
Using the following code:

```rust
generate_api!(interface = Builder, spec = "filename.json");
```

And the following spec:

```json
{
    "openapi": "3.0.0",
    "info": {
        "title": "API",
        "version": "0.0.1"
    },
    "servers": [],
    "components": {
        "schemas": {
            "TimeEntry": {
                "type": "object",
                "required": [],
                "properties": {
                    "client": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "paths": {
        "/time_entries": {
            "get": {
                "summary": "Returns a list of time entries",
                "operationId": "listTimeEntries",
                "parameters": [
                    {
                        "name": "client",
                        "in": "query",
                        "description": "Client",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                ],
                "responses": {
                    "200": {
                        "description": "A JSON array of time-entries",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/TimeEntry"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Results in the following code being generated for the `TimeEntry` component:

```rust
    pub struct ListTimeEntries<'a> {
        client: &'a super::Client,
        client: Result<Option<String>, String>,
    }
```

This breaks with the following exception:

```shell
➜ cargo check
    Checking [redacted] v0.1.0 (/[redacted])
error[E0416]: identifier `client` is bound more than once in the same pattern
 --> src/[redacted].rs:8:1
  |
8 | generate_api!(interface = Builder, spec = "filename.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ used in a pattern more than once

error[E0124]: field `client` is already declared
 --> src/[redacted].rs:8:1
  |
8 | generate_api!(interface = Builder, spec = "filename.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | |
  | field already declared
  | `client` first declared here
  |
  = note: this error originates in the macro `generate_api` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0124, E0416.
For more information about an error, try `rustc --explain E0124`.
error: could not compile `[redacted]` due to 2 previous errors
```

**Comment by dmeijboom** [comment]
The solution would be easy but I'm wondering what approach is better. Prefixing all fields with `param_` for example?

**Comment by ahl** [comment]
Name conflicts are annoying as noted in #261. Here are the properties I think would make for a good solution:

1. Apply to both positional and builder interface styles in a similar way
2. Cover all internal variables (i.e. so we don't need to revisit this and we don't have several partial solutions)
3. Don't dramatically increase the amount of code generated
4. Make it relatively hard to regress in the future

Some proposals:

## prefix all user supplied parameters with `param_`

Not terrible; but kind of gross because those names show up in the rustdoc

## prefix all internal names with some prefix

A little awkward but similar to what e.g. `serde` does. We could make it more ergonomic and harder to screw up by defining a dictionary of these names in the `Generator` struct or via `lazy_static`

## Check for conflicts on the user input and add renames to the code

For example, if there was a parameter called `client` we would notice the conflict and add swap in `param_client` in the builder structure and for the positional code we'd add something like: `let param_client = client` at the top of the `operation_id`-named `fn`.

---

As I consider these, I think I prefer the idea of prefixing all user-supplied names with `param_` (or something), but taking care to show the unprefixed name in any public interfaces that show up in the rustdoc such as the positional argument or the builder methods.

**Comment by dmeijboom** [comment]
@ahl Thanks for the thorough reply. I wasn't aware there was an issue for this already. I'll create an MR to add the `param_` prefix. I understand what you're trying to say btw, one of the best things of the `progenitor` project is that it generates code which is close to what I would have written by hand (unlike [openapi-generato](https://openapi-generator.tech/docs/generators/rust)r).
